# Use Nginx image from Docker Hub
FROM nginx:alpine

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx config file into image
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80
